name: Service CI

on:
  pull_request:
    branches:
      - "main"

env:
  REGION: europe-west1
  PROJECT: listen-and-learn-411214
  REPO: dev
  IMAGE: portfolio-manager

jobs:
  docker-image-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Set vars
        run: |
          echo "IMAGE_TAG_LATEST=$REGION-docker.pkg.dev/$PROJECT/$REPO/$IMAGE:latest" >> $GITHUB_ENV
          echo "IMAGE_TAG_VERSION=$REGION-docker.pkg.dev/$PROJECT/$REPO/$IMAGE:$GITHUB_SHA" >> $GITHUB_ENV

      - name: Google Cloud Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GC_IMAGE_MANAGER_KEY }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Docker auth
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - uses: docker/setup-buildx-action@v3

      - name: Build & push
        uses: docker/build-push-action@v5
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: Dockerfile
          push: true
          tags: ${{ env.IMAGE_TAG_LATEST }},${{ env.IMAGE_TAG_VERSION }}
          provenance: false
